const formatData =  (data) => {   

// removes line breaks,square brackets,backslashes  from chatgpt output
   const cleanData = data.replace(/(\r\n|\n|\r)/gm, "")
   .replace(/\\/g, "")
   .replace(/\[|\]/g, "")
   .replace(/["]+/g, '')

   return cleanData
}

const formatPage=(paragraph,pageCount)=>{
    // divides the whole story generated by chat gpt into pages. pageCount determines how many sentences there are on each page
    const numberOfPages = pageCount


    const sentenceBoundary = /(?<=[.!?])\s+/;
    const sentences = paragraph.split(sentenceBoundary);
    const trimmedSentences = sentences.map((sentence) => sentence.trim());
    const groupedSentences = [];
    let currentGroup = '';



    const linesPerPage = Math.ceil(sentences.length/numberOfPages)

    for (let i = 0; i < trimmedSentences.length; i++) {
        if (i % linesPerPage === 0 && i !== 0) {
        groupedSentences.push(currentGroup);
        currentGroup = '';
        }
        currentGroup += trimmedSentences[i] + ' ';
    }

    if (currentGroup !== '') {
        groupedSentences.push(currentGroup.trim());
    }

    return groupedSentences;
    }

module.exports = {
   
    formatData,
    formatPage
    
   
};
     